version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: waze_postgres
    restart: always
    environment:
      - POSTGRES_USER=waze_user
      - POSTGRES_PASSWORD=waze_password
      - POSTGRES_DB=waze_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # PgAdmin: Interfaz visual para ver la BD (como Mongo Express pero para SQL)
  pgadmin:
    image: dpage/pgadmin4
    container_name: waze_admin_sql
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db