version: '3.8'

services:
  # 1. Base de Datos
  db:
    image: postgis/postgis:15-3.3
    container_name: waze_postgres
    restart: always
    environment:
      - POSTGRES_USER=waze_user
      - POSTGRES_PASSWORD=waze_password
      - POSTGRES_DB=waze_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U waze_user -d waze_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Panel Admin SQL
  pgadmin:
    image: dpage/pgadmin4
    container_name: waze_admin_sql
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  # 3. Cache Redis
  cache:
    image: redis:7.0
    container_name: waze_cache
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--maxmemory", "2mb", "--maxmemory-policy", "allkeys-lru"]

  # 4. Generador de Tráfico (Tu Código Python en Docker)
  traffic-app:
    build: .
    container_name: waze_traffic_generator
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started
    environment:
      - DB_HOST=db       # Nombre del servicio de arriba
      - REDIS_HOST=cache # Nombre del servicio de arriba
    # Comando para ejecutar el generador automáticamente
    command: python -m traffic_generator.generator